CREATE TABLE IF NOT EXISTS computers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  serial_number VARCHAR(255) NOT NULL,
  serial_override VARCHAR(255) NULL,
  manufacturer VARCHAR(255) NULL,
  model VARCHAR(255) NULL,
  operating_system VARCHAR(255) NULL,
  processor TEXT NULL,
  storage TEXT NULL,
  memory VARCHAR(255) NULL,
  gpu TEXT NULL,
  mac_address VARCHAR(255) NULL,
  details TEXT NULL,
  hostname VARCHAR(255) NULL,
  username VARCHAR(255) NULL,
  machine_type VARCHAR(100) NOT NULL,
  acquired_on DATE NULL,
  office VARCHAR(255) NOT NULL,
  par_holder VARCHAR(255) NULL,
  primary_user VARCHAR(255) NULL,
  remarks TEXT NULL,
  collected_on DATETIME(3) NOT NULL,
  script_version VARCHAR(100) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_computers_serial_number (serial_number),
  KEY idx_computers_hostname (hostname),
  KEY idx_computers_office (office)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
